### PR TITLE
Add release drafter CI.

### PR DESCRIPTION
**Pull request by adlerjohn**
Add a CI task to automatically create release drafts with a changelog of PRs.

### CODE REVIEW

**Comment by musalbas** [comment]
Is there any way to make this pull the submodule at https://github.com/lazyledger/docs.lazyledger.io too?

**Review by liamsi — APPROVED** [review]
I'm not familiar with the release-drafter/release-drafter action but given that this seem to work fine in the solidity proto plugin, this LGTM.

**Comment by liamsi** [comment]
To @musalbas question, I think it's at least possible using this event: https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#release
Probably there is another action that can trigger an upload (deployment) after a release is published.

**Comment by adlerjohn** [comment]
@musalbas you can add an action like [this](https://github.com/lazyledger/protobuf3-solidity-lib/blob/master/.github/workflows/npm-publish.yml) to run a command (with a secret token) when a release is published.

**Pull request merged**
